language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=2.2.8
  - CAKE_VERSION=master

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - mv ../cakephp_rest_datasource_plugin plugins/Rest
  - chmod -R 777 ../cakephp/app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis'
      'host' => '',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test Rest Model/Datasource/RestSource --stderr
